### ISSUE TITLE
Import looks for any 'react*' import

### ISSUE THREAD

**Issue by cjcartier** [jpwallace22/react-lazify#9]
**Describe the bug**
If you don't have a react import (or maybe if you do... not 100% tested) it will latch onto another import that has `react` in its name. In this case `react-hook-form`

**Screenshots**
<img width="680" alt="image" src="https://user-images.githubusercontent.com/79073712/213971905-84f4be49-0ec8-47a5-92da-c25378c26c3b.png">

**VS Code information**
 - OS: OSX 12.2.1
 - Version 1.74.3

**Comment by jpwallace22** [comment]
Yup. This is 100% a regex oversight on my part. 
Pretty major issue here.. I'll see if I can't get it patched tomorrow.

**Comment by jpwallace22** [comment]
@cjcartier Thanks again for the bug report. This issue should be corrected in the latest release ([0.4.1](https://github.com/jpwallace22/react-lazify/releases/tag/0.4.1)).
